### ISSUE TITLE
FakeReviewManager not present 

### ISSUE THREAD

**Issue by joonjoonjoon** [google/play-unity-plugins#107]
The documentation mentions FakeReviewManager with examplecode, but I cannot find it in this repository
https://developer.android.com/guide/playcore/in-app-review/test

**Comment by jamcohen** [comment]
Hi @joonjoonjoon,

Thanks for calling this out. The Unity API hasn't been updated to include FakeReviewManager.
I'll make a note for the In App Review team to address this.

In the meantime, as a workaround, you can test by changing [this line](https://github.com/google/play-unity-plugins/blob/95e360ec4bbde268a02fe24951d01b1fb9312eaf/GooglePlayPlugins/com.google.play.review/Runtime/Scripts/Internal/ReviewPlayCoreTaskManager.cs#L38) to:
````
_javaReviewManager = new AndroidJavaObject("com.google.android.play.core.review.testing.FakeReviewManager");
````

Best,
Jake

**Comment by joonjoonjoon** [comment]
I get the following error when trying to launch the reviewmanager, after making the code change you recommended.

```
 AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.UserHandle android.content.Context.getUser()' on a null object reference
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.UserHandle android.content.Context.getUser()' on a null object reference
      at android.app.PendingIntent.getBroadcast(PendingIntent.java:594)
      at com.google.android.play.core.review.testing.FakeReviewManager.requestReviewFlow(Unknown Source:8)
      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
      at android.os.Handler.dispatchMessage(Handler.java:103)
      at android.os.Looper.loop(Looper.java:237)
      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
   at UnityEngine.AndroidJNISafe.CallObjectMethod (System.IntPtr obj, Sy
```


My code for launching the reviewmanager looks like this, based on
https://developer.android.com/guide/playcore/in-app-review/unity

```

    static IEnumerator RequestReviewCoroutine()
    {
        Debug.Log("[AndroidRateGameManager] RequestReviewFlow");

        ReviewManager _reviewManager = new ReviewManager();
        var requestFlowOperation = _reviewManager.RequestReviewFlow();
        yield return requestFlowOperation;
        if (requestFlowOperation.Error != ReviewErrorCode.NoError)
        {
            Debug.LogError("[AndroidRateGameManager] requestFlowOperation.Error: " + requestFlowOperation.Error.ToString());
            yield break;
        }
        var _playReviewInfo = requestFlowOperation.GetResult();

        yield return null; // I Guess???

        Debug.Log("[AndroidRateGameManager] LaunchReviewFlow");

        var launchFlowOperation = _reviewManager.LaunchReviewFlow(_playReviewInfo);
        yield return launchFlowOperation;
        _playReviewInfo = null; // Reset the object
        if (launchFlowOperation.Error != ReviewErrorCode.NoError)
        {
            Debug.LogError("[AndroidRateGameManager] launchFlowOperation.Error: " + launchFlowOperation.Error.ToString());
            yield break;
        }

        Debug.Log("[AndroidRateGameManager] Request Review completed");
    }
```

**Comment by jamcohen** [comment]
Ah, that's my fault. The code I gave you didn't pass in the necessary context. You can try this:
`_javaReviewManager = new AndroidJavaObject("com.google.android.play.core.review.testing.FakeReviewManager", activity);`

That log indicates that the call is resolving properly, which means there is some other condition preventing the review dialog from appearing.

The [troubleshooting](https://developer.android.com/guide/playcore/in-app-review/test#troubleshooting) section in the testing documentation lists the possible reasons.

 Is it possible you have already reviewed the app with your test account?

**Comment by rafanoel** [comment]
Hi @joonjoonjoon, is this still an issue?

**Comment by rafanoel** [comment]
I'm closing this issue, but please feel free to reopen if you need further help.
