### ISSUE TITLE
AssetModuleException

### ISSUE THREAD

**Issue by emiryasar** [google/play-unity-plugins#146]
The game works as expected when installed manually but if dowloaded from play store is not working and instantly closing. I think I started getting this error after updating the sdk. 

logcat returns this error. is it about Play Delivery System ? because error code is writing AssetModuleException.

`[643] gez.accept(8): Request execution failed with error code: -2
com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
	at faz.hg(PG:15)
	at fgt.m(PG:7)
	at dxj.run(PG:2)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
[643] gez.accept(8): Request execution failed with error code: -2
com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
	at faz.hg(PG:15)
	at fgt.m(PG:7)
	at dxj.run(PG:2)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
`

**Comment by emiryasar** [comment]
when I disable separate base apk asset in asset delivery window it works without any error.

**Comment by jamcohen** [comment]
Thanks for reporting this. Could you share the package name and version code of your app with play-unity-plugin-support@googlegroups.com?

Does this happen every time?

**Comment by emiryasar** [comment]
Yes its happen every time when I enable seperate base apk asset. Ok Im sending details and issue to mail

**Comment by emiryasar** [comment]
After the mail, I learned that the problem has been resolved on this issue. My bad.

https://github.com/google/play-unity-plugins/issues/127#issuecomment-884590146

Thank you.
