### ISSUE TITLE
[Play Asset Delivery] build and run option cant signing 

### ISSUE THREAD

**Issue by emiryasar** [google/play-unity-plugins#152]
Google > Build options creates aab successfully but Build and Run option gives me this error. Everytime when I test created new aab and upload google, its taking a lot time how can I solve it ?
 

> Installing app bundle failed: Failed to run 'C:\Program Files\Unity\Hub\Editor\2021.1.23f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -jar "C:\MiniaWarsProject\Assets\GooglePlayPlugins\com.google.android.appbundle\Editor\Tools\bundletool-all.jar" install-apks --adb="D:\AndroidSdk\platform-tools\adb.exe" --apks="C:\Users\EMIR\AppData\Local\Temp\play-unity-build\ymmlx62f.lse\temp.apks"'
stdout:
02:42:15 E/SplitApkInstallerBase: Failed to commit install session 442177973 with command cmd package install-commit 442177973. Error: INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl442177973.tmp/0_base-master has no certificates at entry AndroidManifest.xml 
stderr:
The APKs have been extracted in the directory: C:\Users\EMIR\AppData\Local\Temp\3527727762128714596
The APKs have been extracted in the directory: C:\Users\EMIR\AppData\Local\Temp\3527727762128714596
[BT:1.6.1] Error: Installation of the app failed.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Installation of the app failed.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:154)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$2(InstallApksCommand.java:199)
	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:81)
	at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:43)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:199)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:91)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:49)
Caused by: com.android.ddmlib.InstallException: Failed to commit install session 442177973 with command cmd package install-commit 442177973. Error: INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl442177973.tmp/0_base-master has no certificates at entry AndroidManifest.xml
	at com.android.ddmlib.SplitApkInstallerBase.installCommit(SplitApkInstallerBase.java:99)
	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:85)
	at com.android.ddmlib.internal.DeviceImpl.installPackages(DeviceImpl.java:1117)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:138)
	... 6 more
exit code: 1
UnityEngine.Debug:LogError (object)
Google.Android.AppBundle.Editor.Internal.BuildTools.AppBundleRunner:DisplayRunError (string,string) (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/BuildTools/AppBundleRunner.cs:108)
Google.Android.AppBundle.Editor.Internal.BuildTools.AppBundleRunner:RunBundle (string,Google.Android.AppBundle.Editor.BundletoolBuildMode) (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/BuildTools/AppBundleRunner.cs:65)
Google.Android.AppBundle.Editor.Internal.AppBundlePublisher:RunBundle (string) (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/AppBundlePublisher.cs:223)
Google.Android.AppBundle.Editor.Internal.BuildTools.AppBundleBuilder:HandleUpdate () (at Assets/GooglePlayPlugins/com.google.android.appbundle/Editor/Scripts/Internal/BuildTools/AppBundleBuilder.cs:483)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by DangDinhTho** [comment]
I'm having this problem, and have you solved it yet?

**Comment by emiryasar** [comment]
I inspected what's inside in build created from build&run option and I tried to fix and but couldn't solve it, everytime when I need test, I'm uploading last aab to google and testing. thats not fast way
