### ISSUE TITLE
Crash when start download fast-flow package.

### ISSUE THREAD

**Issue by meichen8050753** [google/play-unity-plugins#153]
Not at all, but very frequently.

2021-10-05 19:12:55.866 19252-19252/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.manasisrefrain, PID: 19252
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{17686cb u0 com.tencent.manasisrefrain/com.google.android.play.core.assetpacks.AssetPackExtractionService}
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2258)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8215)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)

**Comment by 506638093** [comment]
https://zhuanlan.zhihu.com/p/577738203
