### ISSUE TITLE
AssetModuleException, Blcack screen

### ISSUE THREAD

**Issue by Youngchangoon** [google/play-unity-plugins#178]
Unity Version: 2020.3.20f
Plugin Version: 1.7.0
using Other plugin: https://github.com/jelte/be.khepri.play.assetdelivery.addressables

Link the plugin, it will be uploaded to Google Play well even if it exceeds 150mb.

However, when I run the game, I get the following error

How to solve this error?

```
2022-04-26 12:33:08.881 8543-8840/? E/PlayCore: UID: [10297]  PID: [8543] AssetPackServiceImpl : onError(-2)
2022-04-26 12:33:08.890 1266-8909/? E/Finsky: [43160] fla.accept(75): Request execution failed with error code: -2
    com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
        at eqi.Xv(PG:54)
        at euq.l(PG:7)
        at duy.run(PG:5)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by cihadturhan** [comment]
@Youngchangoon what was your solution to this?

**Comment by Youngchangoon** [comment]
I moved game assets to cloudflare r2, and reduced my app size < 150mb  😁
