### ISSUE TITLE
AssetModuleException

### ISSUE THREAD

**Issue by bgsungwon** [google/play-unity-plugins#195]
version : 1.7.0
unity : 2020.3.33f1

When I run the apk build with separate Base APK Asset enabled, an error always occurs on a specific device.

log
2022-08-29 06:26:17.296 1981-4708/? E/Finsky: [197] fxj.a(75): Request execution failed with error code: -2
    com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
        at fcp.XM(PG:69)
        at fgs.l(PG:7)
        at ehl.run(PG:5)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6161)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2022-08-29 06:26:17.298 4785-4797/? I/PlayCore: UID: [10138]  PID: [4785] AssetPackServiceImpl : Leaving the connection open for other ongoing calls.
2022-08-29 06:26:17.298 4785-4797/? E/PlayCore: UID: [10138]  PID: [4785] AssetPackServiceImpl : onError(-2)
2022-08-29 06:26:17.324 1981-4708/? I/Finsky: [197] fkg.<init>(18): com.mobirix.mbsi is installed but certificate mismatch
2022-08-29 06:26:17.350 1981-4708/? E/Finsky: [197] fxj.a(75): Request execution failed with error code: -2
    com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
        at fcp.XM(PG:69)
        at fgs.l(PG:7)
        at ehl.run(PG:5)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6161)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by firdiansyah-ramadhan-programmer** [comment]
up

**Comment by caiguocn** [comment]
up
