### ISSUE TITLE
Not enough storage space to install required resources - AssetModuleException

### ISSUE THREAD

**Issue by noambe** [google/play-unity-plugins#202]
I'm seeing a very strange problem on my Android phone- I have a game published in Google Play that works fine on all of my devices.
Recently, on the same device that used to work just fine, when I download the game from Google Play I get this popup message saying "Error - Not enough storage space to install required resources".
I haven't updated the game on Google Play at all, it just started happening.

Important to note: the game worked fine on the same phone just a few days ago.
My phone's space is fine, I have 40gb free, and I also tried another Unity game of mine and it loads fine.
Phone model: Galaxy S22
This is what I see in the adb logs:

2022-09-27 06:36:10.226 25347-27302 E/Finsky: [303] gid.a(75): Request execution failed with error code: -2
    com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
        at fkv.Yb(PG:69)
        at foy.l(PG:7)
        at eqr.run(PG:5)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2022-09-27 06:36:10.227 27203-27216 E/PlayCore: UID: [10515]  PID: [27203] AssetPackServiceImpl : onError(-2)

I tried:
cleaning Google Play cache
reboot phone
uninstall/reinstall multiple times from different accounts.

Still repros- any idea??

**Comment by tromagon** [comment]
Currently facing the exact same issue, did you manage to fix it?

**Comment by noambe** [comment]
> Currently facing the exact same issue, did you manage to fix it?

No. I was only able to understand why the problem happens, but not a solution. It's related to Android not deleting the app folder from the external memory after uninstall. My next step is to factory reset the phone...

See my other post here: https://forum.unity.com/threads/app-uninstall-doesnt-clean-folder-inside-storage-emulated-0-android-data.1353758/#post-8544083

**Comment by noambe** [comment]
> Currently facing the exact same issue, did you manage to fix it?

Can you write your device model? I just heard of another S22 that can't install my app.

**Comment by tromagon** [comment]
> Can you write your device model? I just heard of another S22 that can't install my app.

Phone is a Galaxy S22+
Model number is SM-S906W

**Comment by noambe** [comment]
It sure looks like a problem with S22 then. I updated my post in this forum, and also opened a ticket on Samsung. Now it's just hoping that the right eyes see that.
https://forum.unity.com/threads/samsung-s22-broken-with-unity-not-enough-storage-space-to-install-required-resources-100-repro.1349477/#post-8592478

**Comment by tromagon** [comment]
Would this occur if you were to post resulting build on the store? 
Also does this happen when debugging directly from Unity?

**Comment by noambe** [comment]
Yes for both. 
You can download my game: https://play.google.com/store/apps/details?id=NoamStudios.Games.MegaTicTacToeFree&hl=en_US&gl=US&pli=1

**Comment by tromagon** [comment]
I did a factory reset of the phone, so it was okay for a while then the issue started happening again.
I tried your game and the steps you provided, the bug occurs 100%
Any progress on your end?

**Comment by noambe** [comment]
No, at this point Samsung and Unity needs to figure this out between themselves. So far I opened tickets for both of them, but it's not getting traction. I wish I had better way to escalate. 
It seems to be happening just on S22, so I simply avoid testing on this device.

**Comment by guenthereder** [comment]
> No, at this point Samsung and Unity needs to figure this out between themselves. So far I opened tickets for both of them, but it's not getting traction. I wish I had better way to escalate.
> It seems to be happening just on S22, so I simply avoid testing on this device.

I seem to have run into a similar problem, also with an S22.

**Comment by noambe** [comment]
If anyone has good connections with either Samsung or Unity, please help escalate to their eng team. As of now I'm not getting any traction from any of them being a single developer.

**Comment by End2417** [comment]
I managed to fix it by doing the following: delete the data folder (Android/data (not sure if it's necessary, but just to be safe)), clear your app data/cache, and give storage permission before opening the app.

I'm pretty sure it should work. Gl.

**Comment by KitoKato7** [comment]
I have the same issue, this occur after I use SDMaid pro to clean my Mi 8, and after that crash keep happening, so I enable Storage Permission before open the app -> open the app then wait a bit . then bom the app works normally again

**Comment by shivashiva88859-dot** [comment]
Shiva Shiva
