### ISSUE TITLE
AssetModuleException: Session not found

### ISSUE THREAD

**Issue by fNathan123** [google/play-unity-plugins#229]
Hello, We have some issue with updating our application. Our application download progress often stuck at 100% at google play store then we checked our Logcat and found this error after we clicked update button.

`
[57617] kvk.apply(1280): Failed to retrieve session -1.
com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Session not found.
`
We suspect this error caused this since this error didn't appear if the download is succeed. may I know what caused this?

ps : we are using Play Asset Delivery
Thanks!

**Comment by mtemnikov** [comment]
unity : 2021.3.28f1

We have the same problem. Also some times play asset delivery on demand assets download are stucked with no further progress. Only clean play store app cached might help sometimes (but not in all cases). However we are unable to deliver this information to large amount of users ;(

**Comment by mtemnikov** [comment]
So any news?( It is very hard problem for us.

**Comment by fNathan123** [comment]
Unfortunately no bud, we are also confused as you do LMAO. We can only advice the users to clear the google playstore's cache/data if there's something wrong with the downloading stuff. But we can't just tell our user to clear the playstore's data every time. I'm pretty sure the problem is on google side and I want some verification from google if there's something we can do.

But, from our side these problem typically occurred if we remove some asset packs or changing asset packs name (we are using custom asset packs).

**Comment by mtemnikov** [comment]
```
2023.12.04 20:55:47.769 5399 5749 Error Finsky [397] kzz.a(843): Request execution failed with error code: -2
2023.12.04 20:55:47.769 5399 5749 Error Finsky com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at jqx.aft(PG:533)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at jwj.k(PG:75)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at ixz.run(PG:230)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at android.os.Handler.handleCallback(Handler.java:873)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at android.os.Handler.dispatchMessage(Handler.java:99)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at android.os.Looper.loop(Looper.java:193)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at android.app.ActivityThread.main(ActivityThread.java:6737)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at java.lang.reflect.Method.invoke(Native Method)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2023.12.04 20:55:47.769 5399 5749 Error Finsky 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

Some debug on bundle downloading at com.android.vending process. We are getting this error some times. Possible step to reproduce (not in 100%) is to close app and restore it immediately.

**Comment by fNathan123** [comment]
Yes we got the same error as well

![error_caused_missing_pack](https://github.com/google/play-unity-plugins/assets/99603564/26f3c56c-d99f-4198-9a74-cc0c300c9bb0)

**Comment by mtemnikov** [comment]
Did you report on unity forum?

**Comment by fNathan123** [comment]
not yet

**Comment by yagodar** [comment]
Hi, +1 to you, folks. We got the same stuck on update 100%. We have also changed the asset packs and we are using PAD with Unity

**Comment by firdiar-mita** [comment]
upup +1

**Comment by yagodar** [comment]
Hello again :) Finally we've found a workaround.

It turns out, that the key in our errors was the name of existing asset pack.

1) In old version we had name of the asset pack "CustomOnDemand"
2) In new version we've changed the name of this asset pack to "CustomRaceOneOnDemand"
3) We got stuck on Update the app inside Google Play app at 100%.

Workaround:
**Keep the name of existing asset packs and make it exists in newer versions**
After change name back from "CustomRaceOneOnDemand" to "CustomOnDemand" there is no stuck at 100% on Update :tada:

It's definitely a bug of PAD. 
So please, fix it for others, who didn't reach this thread.

**Comment by fNathan123** [comment]
alright, this will be ugly if you use fast-follow asset packs, but I have some question.. after all those download stuck we decided to revert all the PAD changes we've made. Those packs downloaded normally at playstore but google returns internal error for all of our packs when we tried to fetch asset pack's state in our app.

Not sure what it was but I will keep in mind to be careful if we decide to change the pack structures :(
so did you leave the old packs empty? Or do you leave some files inside there?

**Comment by mtemnikov** [comment]
Thanks for work around. It will save our time in future. But unfortunately we are still getting stuck on download packs.

This is unity forum topic and some info

https://forum.unity.com/threads/update-play-core-lib-or-fix-critical-error.1525768/#post-9524083

**Comment by yagodar** [comment]
For the record - we leave exact same assets in our "CustomOnDemand", just updated the content inside it. So I think google`s patch system worked in this case and our app not stucked.

**Comment by ozerelkerem** [comment]
We are experiencing the same problem. When we click the "Update" button in the Play Store, it shows "Pending" for a second and then reverts to the "Update" button. The update does not proceed. We’ve tried clearing the Google Play Store cache, which temporarily resolves the issue, but we can’t expect every user to do this.

We tried to update com.google.play.assetdelivery to 1.9.4 version but nothing changed.

2025/02/11 21:17:12.953 5832 6025 Info Finsky [285] bb.a(146): Skipped download state update for download 392 on initialize. java.util.concurrent.ExecutionException: com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Session not found.


2025.02.11 17:33:13.447 3240 6236 Error Finsky com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.

![Image](https://github.com/user-attachments/assets/6970c1bd-7438-4eb5-93e7-e3dd7f06a099)
