### ISSUE TITLE
Crash MissingForegroundServiceTypeException

### ISSUE THREAD

**Issue by dimmduh** [google/play-unity-plugins#235]
android.app.MissingForegroundServiceTypeException at com.google.android.play:asset-delivery@@2.0.2:3

Unity 2022.3.15f1
Android 14
AssetDelivery 1.8.2

android.app.MissingForegroundServiceTypeException at com.google.android.play:asset-delivery@@2.0.2:3
`android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{9cfd86a 10459:com.games..survive/u0a367} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
	at android.app.Service.startForeground(Service.java:775)
	at com.google.android.play.core.assetpacks.ci.onServiceConnected(com.google.android.play:asset-delivery@@2.0.2:3)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2313)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2350)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

**Comment by whitingm-usc** [comment]
I'm getting this now as well.
Unity 2021.3.34f1
Android 14
AssetDelivery 1.8.2

**Comment by vizgl** [comment]
Is there some workaround for this?

**Comment by firdiar-mita** [comment]
bumb
