### ISSUE TITLE
Many crashes on samsungs

### ISSUE THREAD

**Issue by dimmduh** [google/play-unity-plugins#92]
`java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.8f1 (60781d942082)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'samsung/m30sdd/m30s:11/RP1A.200720.012/M307FXXU4CUAG:user/release-keys'
Revision: '5'
ABI: 'arm64'
Timestamp: 2021-03-18 13:26:10+0530
pid: 15736, tid: 18300, name: UnityGfxDeviceW  >>> com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishi <<<
uid: 10338
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x399
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000000000000001  x3  0000000000000055
    x4  0000000000000021  x5  0000000000000048  x6  0000007a51d05000  x7  00000000077925c6
    x8  0000000000000001  x9  78403952944c1ffc  x10 0000000000000001  x11 0000000000000000
    x12 00000076c04bdc40  x13 000000000000004d  x14 0000000000000000  x15 0000000040000000
    x16 000000774eed1960  x17 0000007a4fbd26cc  x18 000000040000002f  x19 000000774eefe740
    x20 00000075e654b050  x21 000000774eefe7e8  x22 0000000000000073  x23 000000774eeedb90
    x24 0000000000000010  x25 000000000000001c  x26 000000000000001c  x27 000000774eeef3c6
    x28 0000000000000018  x29 0000000000003234
    sp  00000076c04bf6a0  lr  000000774e54052c  pc  000000774e540574

backtrace:
      #00 pc 000000000077a574  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #01 pc 000000000077a114  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #02 pc 000000000077a064  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #03 pc 0000000000203b58  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #04 pc 0000000000205e00  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #05 pc 000000000025f240  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #06 pc 000000000025f148  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #07 pc 000000000025f3dc  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #08 pc 000000000025f88c  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #09 pc 000000000025f918  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #10 pc 00000000005a245c  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #11 pc 00000000008c8e74  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #12 pc 00000000008cbdf4  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #13 pc 00000000008c3268  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #14 pc 000000000032a6f8  /data/app/~~B9S6M1MbRmQdAfwWSFpyEA==/com.mega_play_games.ocean.raft.shark.craft.survival_games.crafting.building.last_day.survive.fishing.hungry-_27Wx7MlMOYor6F19fzswg==/lib/arm64/libunity.so (BuildId: 5e9ae4a07423b3bfc2e824e9a04b5c8a55c26c6e)
      #15 pc 00000000000afef8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 5e331d2d6b87a9d7a6c0c2bce3181824)
      #16 pc 00000000000503f8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 5e331d2d6b87a9d7a6c0c2bce3181824)

	at libunity.0x77a574(Native Method)
	at libunity.0x77a114(Native Method)
	at libunity.0x77a064(Native Method)
	at libunity.0x203b58(Native Method)
	at libunity.0x205e00(Native Method)
	at libunity.0x25f240(Native Method)
	at libunity.0x25f148(Native Method)
	at libunity.0x25f3dc(Native Method)
	at libunity.0x25f88c(Native Method)
	at libunity.0x25f918(Native Method)
	at libunity.0x5a245c(Native Method)
	at libunity.0x8c8e74(Native Method)
	at libunity.0x8cbdf4(Native Method)
	at libunity.0x8c3268(Native Method)
	at libunity.0x32a6f8(Native Method)
	at libc.__pthread_start(void*)(__pthread_start:64)
	at libc.__start_thread(__start_thread:64)

#0. AssetPackBackgroundExecutor
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#1. AssetPackService
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#2. AudioPortEventHandler
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#3. AudioThread

#4. AudioTrack

#5. Binder:15736_1

#6. Binder:15736_2

#7. Binder:15736_3

#8. Binder:15736_4

#9. Chrome_IOThread

#10. Chrome_InProcGpuThread

#11. Chrome_ProcessLauncherThread
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#12. CleanupReference
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at CM.run(chromium-TrichromeWebViewGoogle.aab-stable-428010133:2)

#13. ConnectivityThread
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#14. FMOD Studio bank load thread

#15. FMOD Studio sample load thread

#16. FMOD Studio update thread

#17. FMOD file thread

#18. FMOD mixer thread

#19. FMOD nonblocking thread (0)

#20. FMOD stream thread

#21. FinalizerDaemon
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:923)

#22. FinalizerWatchdogDaemon
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.Object.wait(Object.java:568)
	at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:341)
	at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:321)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:923)

#23. Firebase-Messaging-Init
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.5.0:6)
	at java.lang.Thread.run(Thread.java:923)

#24. Firebase-Messaging-Topics-Io
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.5.0:6)
	at java.lang.Thread.run(Thread.java:923)

#25. FocusHandlerThread
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#26. GoogleApiHandler
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#27. HeapTaskDaemon

#28. InsetsAnimations
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#29. JavaBridge
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#30. Jit thread pool worker thread 0

#31. MemoryInfra

#32. OSH_NetworkHandlerThread
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#33. OSH_WritePrefs
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#34. OkHttp ConnectionPool
	at java.lang.Object.wait(Native Method)
	at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#35. Okio Watchdog
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.Object.wait(Object.java:568)
	at com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:313)
	at com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:42)
	at com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:288)

#36. PlatformServiceBridgeHandlerThread
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#37. PlayBillingLibrary-1
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#38. PlayBillingLibrary-2
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#39. PlayBillingLibrary-3
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#40. PlayBillingLibrary-4
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#41. PlayBillingLibrary-5
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#42. PlayBillingLibrary-6
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#43. PlayBillingLibrary-7
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#44. Profile Saver

#45. ReferenceQueueDaemon
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.Object.wait(Object.java:568)
	at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:923)

#46. Signal Catcher

#47. ThreadPoolForeg

#48. UnityChoreographer
	at bitter.jnibridge.JNIBridge.invoke(Native Method)
	at bitter.jnibridge.JNIBridge$a.invoke(Unknown Source)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy14.doFrame(Unknown Source)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#49. UnityMain
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.access$300(Unknown Source)
	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:246)
	at com.unity3d.player.UnityPlayer$e.run(Unknown Source)

#50. YMM-APT-1
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#51. YMM-BD-4
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.yandex.metrica.impl.ob.eh$1.run(SourceFile:93)
	at java.lang.Thread.run(Thread.java:923)

#52. YMM-DW-2
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.Object.wait(Object.java:568)
	at com.yandex.metrica.impl.ob.lx$a.run(SourceFile:84)

#53. YMM-RS-5
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#54. YMM-YM-3
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)

#55. pool-12-thread-1
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#56. pool-12-thread-2
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#57. pool-12-thread-3
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#58. pool-12-thread-4
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#59. pool-12-thread-5
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#60. pool-12-thread-6
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#61. pool-12-thread-7
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#62. pool-12-thread-8
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#63. pool-7-thread-1
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

#64. queued-work-looper
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by dimmduh** [comment]
![image](https://user-images.githubusercontent.com/446814/111611751-c07d6200-8817-11eb-81f5-5414570dd6d0.png)

**Comment by arimintzu** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/446814/111611751-c07d6200-8817-11eb-81f5-5414570dd6d0.png)

Do you have any solution for this now?
My players from Samsung also crashes & lags since I used PlayAssetDelivery :(

**Comment by dimmduh** [comment]
> > ![image](https://user-images.githubusercontent.com/446814/111611751-c07d6200-8817-11eb-81f5-5414570dd6d0.png)
> 
> Do you have any solution for this now?
> My players from Samsung also crashes & lags since I used PlayAssetDelivery :(

Still no. It's crashing and crashing (
No one gonna fix it.
